runtime: php72
api_version: 1
handlers:
- url: /signatures/central
  static_files: www/central.html
  upload: www/central.html
- url: /signatures/de-cc
  static_files: www/de-cc.html
  upload: www/de-cc.html
- url: /signatures/de-sales
  static_files: www/de-sales.html
  upload: www/de-sales.html
- url: /signatures/fr-cc
  static_files: www/fr-cc.html
  upload: www/fr-cc.html
- url: /signatures/fr-sales
  static_files: www/fr-sales.html
  upload: www/fr-sales.html
- url: /signatures/se-cc
  static_files: www/se-cc.html
  upload: www/se-cc.html
- url: /signatures/se-ops
  static_files: www/se-ops.html
  upload: www/se-ops.html
- url: /signatures/se-sales
  static_files: www/se-sales.html
  upload: www/se-sales.html
- url: /signatures/js/script.js
  script: www/js/script.js
  upload: www/js/script.js
- url: /signatures/css/style.css
  static_files: www/css/style.css
  upload: www/css/style.css
- url: /signatures/ajax_php_file.php
  script: www/signatures/ajax_php_file.php
  upload: www/signatures/ajax_php_file.php
- url: /signatures/(.*)
  static_files: www/index.html
  upload: www/index.html
