runtime: php72
api_version: 1
threadsafe: true
handlers:
- url: /central
  script: central.php
- url: /js/script.js
  script: /js/script.js
- url: /css/style.css
  script: /css/style.css
- url: /.*
  script: index.html
