runtime: php72
api_version: 1
handlers:
- url: /signatures/central
  static_files: signatures/central.html
  upload: signatures/central.html
- url: /signatures/fr-central
  static_files: signatures/fr-central.html
  upload: signatures/fr-central.html
- url: /signatures/de-cc
  static_files: signatures/de-cc.html
  upload: signatures/de-cc.html
- url: /signatures/de-sales
  static_files: signatures/de-sales.html
  upload: signatures/de-sales.html
- url: /signatures/fr-cc
  static_files: signatures/fr-cc.html
  upload: signatures/fr-cc.html
- url: /signatures/fr-sales
  static_files: signatures/fr-sales.html
  upload: signatures/fr-sales.html
- url: /signatures/se-cc
  static_files: signatures/se-cc.html
  upload: signatures/se-cc.html
- url: /signatures/se-ops
  static_files: signatures/se-ops.html
  upload: signatures/se-ops.html
- url: /signatures/se-sales
  static_files: signatures/se-sales.html
  upload: signatures/se-sales.html
- url: /signatures/js/script.js
  static_files: signatures/js/script.js
  upload: signatures/js/script.js
- url: /signatures/css/style.css
  static_files: signatures/css/style.css
  upload: signatures/css/style.css
- url: /signatures/ajax_php_file.php
  script: signatures/ajax_php_file.php
- url: /signatures/(.*)
  static_files: signatures/index.html
  upload: signatures/index.html
- url: /signatures
  static_files: signatures/index.html
  upload: signatures/index.html

# Serve images as static resources.
- url: /(.+\.(css|gif|png|jpg|js|json|mo|po))$
  static_files: \1
  upload: .+\.(css|gif|png|jpg|js|json|mo|po)$
- url: .*
  script: auto
  secure: always
  redirect_http_response_code: 301